/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_tiffannyvarela;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author tiffa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JButton();
        txt_contra = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        jd_contra = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txt_nuevacontrasena = new javax.swing.JTextField();
        btn_agregarcontra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_key = new javax.swing.JTextField();
        jd_crearmundo = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        agregarmundo = new javax.swing.JButton();
        txt_nombremundo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cmb_criaturasmundo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jd_vermundos = new javax.swing.JDialog();
        jd_mostrar = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_criaturas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_mundos = new javax.swing.JList<>();
        btn_agregarmundo = new javax.swing.JButton();
        btn_agregarcriatura = new javax.swing.JButton();
        btn_modificarmundo = new javax.swing.JButton();
        btn_modificarcriatura = new javax.swing.JButton();
        btn_agregarmundo3 = new javax.swing.JButton();
        btn_mostrarmundo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jd_crearcriatura = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_region = new javax.swing.JTextField();
        txt_maxanios = new javax.swing.JTextField();
        txt_nombrecriatura = new javax.swing.JTextField();
        txt_objetos = new javax.swing.JTextField();
        txt_cantidadenergia = new javax.swing.JTextField();
        txt_vivas = new javax.swing.JTextField();
        btn_agregarcri = new javax.swing.JButton();
        jd_modificarmundo = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        txt_nombremundo1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmb_elegircri = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cmb_mundos = new javax.swing.JComboBox<>();
        jd_modificarcriatura = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        cmb_criaturas = new javax.swing.JComboBox<>();
        btn_agregarcri1 = new javax.swing.JButton();
        txt_objetos1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_vivas1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_region1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_maxanios1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_cantidadenergia1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_nombrecriatura1 = new javax.swing.JTextField();
        Barra = new javax.swing.JMenuBar();
        jm_login = new javax.swing.JMenu();
        jmi_entrar = new javax.swing.JMenuItem();
        jmi_contra = new javax.swing.JMenuItem();
        jm_muestra = new javax.swing.JMenu();
        jmi_mostrar = new javax.swing.JMenuItem();

        jLabel3.setText("Usuario");

        jLabel4.setText("Contrasena");

        btn_entrar.setText("Entrar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txt_usuario)))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jLabel1.setText("Contrasena");

        btn_agregarcontra.setText("Agregar");
        btn_agregarcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcontraActionPerformed(evt);
            }
        });

        jLabel2.setText("Key");

        javax.swing.GroupLayout jd_contraLayout = new javax.swing.GroupLayout(jd_contra.getContentPane());
        jd_contra.getContentPane().setLayout(jd_contraLayout);
        jd_contraLayout.setHorizontalGroup(
            jd_contraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_contraLayout.createSequentialGroup()
                .addGroup(jd_contraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_contraLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btn_agregarcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_contraLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jd_contraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jd_contraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nuevacontrasena)
                            .addComponent(txt_key, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jd_contraLayout.setVerticalGroup(
            jd_contraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_contraLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jd_contraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_contraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nuevacontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btn_agregarcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jLabel8.setText("Nombre");

        agregarmundo.setText("Agregar Mundo");
        agregarmundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarmundoActionPerformed(evt);
            }
        });

        jLabel25.setText("Criaturas");

        cmb_criaturasmundo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar criatura" }));

        jButton4.setText("Agregar Criatura");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearmundoLayout = new javax.swing.GroupLayout(jd_crearmundo.getContentPane());
        jd_crearmundo.getContentPane().setLayout(jd_crearmundoLayout);
        jd_crearmundoLayout.setHorizontalGroup(
            jd_crearmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearmundoLayout.createSequentialGroup()
                .addGroup(jd_crearmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearmundoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jd_crearmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel25))
                        .addGap(34, 34, 34)
                        .addGroup(jd_crearmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombremundo)
                            .addComponent(cmb_criaturasmundo, 0, 271, Short.MAX_VALUE)))
                    .addGroup(jd_crearmundoLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jd_crearmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agregarmundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jd_crearmundoLayout.setVerticalGroup(
            jd_crearmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearmundoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_crearmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nombremundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jd_crearmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cmb_criaturasmundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(agregarmundo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_vermundosLayout = new javax.swing.GroupLayout(jd_vermundos.getContentPane());
        jd_vermundos.getContentPane().setLayout(jd_vermundosLayout);
        jd_vermundosLayout.setHorizontalGroup(
            jd_vermundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_vermundosLayout.setVerticalGroup(
            jd_vermundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Mostrar");

        jLabel6.setText("Mundos");

        jLabel7.setText("Criaturas");

        jl_criaturas.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_criaturas);

        jl_mundos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_mundos);

        btn_agregarmundo.setText("Agregar");
        btn_agregarmundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarmundoActionPerformed(evt);
            }
        });

        btn_agregarcriatura.setText("Agregar");
        btn_agregarcriatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcriaturaActionPerformed(evt);
            }
        });

        btn_modificarmundo.setText("Modificar");
        btn_modificarmundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarmundoActionPerformed(evt);
            }
        });

        btn_modificarcriatura.setText("Modificar");
        btn_modificarcriatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarcriaturaActionPerformed(evt);
            }
        });

        btn_agregarmundo3.setText("Crear Reporte");
        btn_agregarmundo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarmundo3ActionPerformed(evt);
            }
        });

        btn_mostrarmundo.setText("Crear Reporte");
        btn_mostrarmundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarmundoActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar Reporte");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_mostrarLayout = new javax.swing.GroupLayout(jd_mostrar.getContentPane());
        jd_mostrar.getContentPane().setLayout(jd_mostrarLayout);
        jd_mostrarLayout.setHorizontalGroup(
            jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mostrarLayout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mostrarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregarmundo)
                    .addComponent(btn_modificarmundo)
                    .addComponent(btn_mostrarmundo)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btn_agregarcriatura)
                    .addComponent(btn_modificarcriatura)
                    .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_agregarmundo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
        );
        jd_mostrarLayout.setVerticalGroup(
            jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarmundo)
                    .addComponent(btn_agregarcriatura))
                .addGap(18, 18, 18)
                .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificarcriatura)
                    .addComponent(btn_modificarmundo))
                .addGap(18, 18, 18)
                .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarmundo3)
                    .addComponent(btn_mostrarmundo))
                .addGap(18, 18, 18)
                .addGroup(jd_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel9.setText("Nombre");

        jLabel10.setText("Cantidad de energia");

        jLabel11.setText("Maximo de anios");

        jLabel12.setText("Region");

        jLabel13.setText("Cantidad de especies vivas");

        jLabel14.setText("Objetos magicos");

        btn_agregarcri.setText("Agregar criatura");
        btn_agregarcri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearcriaturaLayout = new javax.swing.GroupLayout(jd_crearcriatura.getContentPane());
        jd_crearcriatura.getContentPane().setLayout(jd_crearcriaturaLayout);
        jd_crearcriaturaLayout.setHorizontalGroup(
            jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                .addGroup(jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(42, 42, 42)
                                .addComponent(txt_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(41, 41, 41)
                                .addComponent(txt_region, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(33, 33, 33)
                                .addComponent(txt_maxanios, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(53, 53, 53)
                                .addComponent(txt_vivas, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cantidadenergia, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nombrecriatura, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btn_agregarcri, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jd_crearcriaturaLayout.setVerticalGroup(
            jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcriaturaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_nombrecriatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_cantidadenergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_maxanios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_vivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jd_crearcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btn_agregarcri, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel15.setText("Nombre");

        jLabel16.setText("Criaturas");

        cmb_elegircri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar criatura" }));

        jButton1.setText("Modificar");

        jLabel17.setText("Mundos");

        cmb_mundos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mundos" }));
        cmb_mundos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_mundosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarmundoLayout = new javax.swing.GroupLayout(jd_modificarmundo.getContentPane());
        jd_modificarmundo.getContentPane().setLayout(jd_modificarmundoLayout);
        jd_modificarmundoLayout.setHorizontalGroup(
            jd_modificarmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarmundoLayout.createSequentialGroup()
                .addGroup(jd_modificarmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarmundoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jd_modificarmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(34, 34, 34)
                        .addGroup(jd_modificarmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombremundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_elegircri, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_mundos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_modificarmundoLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jd_modificarmundoLayout.setVerticalGroup(
            jd_modificarmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarmundoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jd_modificarmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmb_mundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_modificarmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_nombremundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jd_modificarmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmb_elegircri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jLabel18.setText("Criaturas");

        cmb_criaturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cmb_criaturas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_criaturasItemStateChanged(evt);
            }
        });

        btn_agregarcri1.setText("Modificiar criatura");
        btn_agregarcri1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcri1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Objetos magicos");

        jLabel20.setText("Cantidad de especies vivas");

        jLabel21.setText("Region");

        jLabel22.setText("Maximo de anios");

        jLabel23.setText("Cantidad de energia");

        jLabel24.setText("Nombre");

        javax.swing.GroupLayout jd_modificarcriaturaLayout = new javax.swing.GroupLayout(jd_modificarcriatura.getContentPane());
        jd_modificarcriatura.getContentPane().setLayout(jd_modificarcriaturaLayout);
        jd_modificarcriaturaLayout.setHorizontalGroup(
            jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(42, 42, 42)
                        .addComponent(txt_objetos1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(41, 41, 41)
                        .addComponent(txt_region1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(33, 33, 33)
                        .addComponent(txt_maxanios1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(53, 53, 53)
                        .addComponent(txt_vivas1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cantidadenergia1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nombrecriatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btn_agregarcri1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_criaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jd_modificarcriaturaLayout.setVerticalGroup(
            jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarcriaturaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmb_criaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_nombrecriatura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt_cantidadenergia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_maxanios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_region1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_vivas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jd_modificarcriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_objetos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btn_agregarcri1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_login.setText("Login");

        jmi_entrar.setText("Entrar");
        jmi_entrar.setEnabled(false);
        jmi_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_entrarActionPerformed(evt);
            }
        });
        jm_login.add(jmi_entrar);

        jmi_contra.setText("Crear contrasena");
        jmi_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_contraActionPerformed(evt);
            }
        });
        jm_login.add(jmi_contra);

        Barra.add(jm_login);

        jm_muestra.setText("Listas");
        jm_muestra.setEnabled(false);

        jmi_mostrar.setText("Mostrar");
        jmi_mostrar.setEnabled(false);
        jmi_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mostrarActionPerformed(evt);
            }
        });
        jm_muestra.add(jmi_mostrar);

        Barra.add(jm_muestra);

        setJMenuBar(Barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcontraActionPerformed
        // TODO add your handling code here:
        adminUsuarios au = new adminUsuarios("./credenciales.txt");
        String contra=txt_nuevacontrasena.getText(),nueva="";
        int as,n,key=Integer.parseInt(txt_key.getText());
        char let;
        try {
            for (int i = 0; i < contra.length(); i++) {
            as = contra.codePointAt(i);
            if (as==122) {
                as=65;
            }
            
            if (as==90) {
                as=97;
            }
            n=as+key;
            let=(char)n;
            nueva+=let;
        }
        Usuario u = new Usuario(user, nueva, key);
        au.getUsuario().add(u);
        au.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Guardado");
        jmi_entrar.setEnabled(true);
        txt_key.setText("");
        txt_nuevacontrasena.setText("");
            System.out.println(au.getUsuario());
        } catch (Exception e) {
        }

        
    }//GEN-LAST:event_btn_agregarcontraActionPerformed

    private void jmi_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_contraActionPerformed
        // TODO add your handling code here:
        jd_contra.setModal(true);
        jd_contra.pack();
        jd_contra.setLocationRelativeTo(this);
        jd_contra.setVisible(true);
    }//GEN-LAST:event_jmi_contraActionPerformed

    private void jmi_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_entrarActionPerformed
        // TODO add your handling code here:
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }//GEN-LAST:event_jmi_entrarActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        // TODO add your handling code here:
        adminUsuarios au = new adminUsuarios("./credenciales.txt");
        String cifrada=au.getUsuario().get(WIDTH-1).getContra();
        int key = au.getUsuario().get(WIDTH-1).getKey(),n;
        System.out.println(key);
        System.out.println(cifrada);
        char let;
        String nueva="";
        try {
         for (int i = 0; i < cifrada.length(); i++) {
            int as = cifrada.codePointAt(i);
            if (as==97) {
                as=90;
            }
            
            if (as==65) {
                as=122;
            }
            n=as+key;
            let=(char)n;
            nueva+=let;
        }
        
            if (txt_usuario.getText().equals(user)&&txt_contra.getText().equals(nueva)) {
                JOptionPane.showMessageDialog(jd_login, "Ingreso con exito");
                jm_muestra.setEnabled(true);
                jmi_mostrar.setEnabled(true);
                jd_login.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_login, "Error");
        }
//        jm_muestra.setEnabled(true);
//                jmi_mostrar.setEnabled(true);
//                jd_login.setVisible(false);
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_agregarmundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarmundoActionPerformed
        // TODO add your handling code here:
        jd_crearmundo.setModal(true);
        jd_crearmundo.pack();
        jd_crearmundo.setLocationRelativeTo(this);
        jd_crearmundo.setVisible(true);
    }//GEN-LAST:event_btn_agregarmundoActionPerformed

    private void btn_agregarcriaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcriaturaActionPerformed
        // TODO add your handling code here:
        jd_crearcriatura.setModal(true);
        jd_crearcriatura.pack();
        jd_crearcriatura.setLocationRelativeTo(this);
        jd_crearcriatura.setVisible(true);
    }//GEN-LAST:event_btn_agregarcriaturaActionPerformed

    private void jmi_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mostrarActionPerformed
        // TODO add your handling code here:
        jd_mostrar.setModal(true);
        jd_mostrar.pack();
        jd_mostrar.setLocationRelativeTo(this);
        jd_mostrar.setVisible(true);
    }//GEN-LAST:event_jmi_mostrarActionPerformed

    private void btn_agregarcriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcriActionPerformed
        // TODO add your handling code here:
        String nombre,region,objeto;
        int energia,anios,vidas;
        Criatura cri;
        
        try {
            nombre=txt_nombrecriatura.getText();
            region=txt_region.getText();
            objeto=txt_objetos.getText();
            anios=Integer.parseInt(txt_maxanios.getText());
            energia=Integer.parseInt(txt_cantidadenergia.getText());
            vidas=Integer.parseInt(txt_vivas.getText());
            Criatura c = new Criatura(nombre, energia, anios, region, vidas);
            c.addObjeto(txt_objetos.getText());
            DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
        modelo.addElement(c);
        jl_criaturas.setModel(modelo);
        DefaultComboBoxModel modelocmb =(DefaultComboBoxModel) cmb_criaturas.getModel();
            modelocmb.addElement(c);
        cmb_criaturas.setModel(modelocmb);
        cmb_criaturasmundo.setModel(modelocmb);
        txt_nombrecriatura.setText("");
        txt_region.setText("");
        txt_objetos.setText("");
        txt_cantidadenergia.setText("");
        txt_maxanios.setText("");
        txt_vivas.setText("");
        
            
            JOptionPane.showMessageDialog(this, "Criatura guardada");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btn_agregarcriActionPerformed

    private void agregarmundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarmundoActionPerformed
        // TODO add your handling code here:
        try {
            String nombre=txt_nombremundo.getText();
            Mundo_disco md = new Mundo_disco(nombre);
            DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
            modelo.addElement(md);
            jl_mundos.setModel(modelo);
            
            DefaultComboBoxModel modelocmb =(DefaultComboBoxModel) cmb_mundos.getModel();
            modelocmb.addElement(nombre);
            cmb_mundos.setModel(modelocmb);
            JOptionPane.showMessageDialog(this, "Mundo guardado");
            txt_nombremundo.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_agregarmundoActionPerformed

    private void btn_modificarmundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarmundoActionPerformed
        // TODO add your handling code here:
        jd_modificarmundo.setModal(true);
        jd_modificarmundo.pack();
        jd_modificarmundo.setLocationRelativeTo(this);
        jd_modificarmundo.setVisible(true);                                
    }//GEN-LAST:event_btn_modificarmundoActionPerformed

    private void btn_modificarcriaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarcriaturaActionPerformed
        // TODO add your handling code here:
        jd_modificarcriatura.setModal(true);
        jd_modificarcriatura.pack();
        jd_modificarcriatura.setLocationRelativeTo(this);
        jd_modificarcriatura.setVisible(true);   
    }//GEN-LAST:event_btn_modificarcriaturaActionPerformed

    private void btn_agregarmundo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarmundo3ActionPerformed
        // TODO add your handling code here:
        int pos = jl_criaturas.getSelectedIndex();
        DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
        adminCriaturas ac = new adminCriaturas("./Criaturas/"+((Criatura)modelo.get(pos)).getNombre()+".txt");
        try {
            Criatura c = new Criatura(((Criatura)modelo.get(pos)).getNombre(), 
                    ((Criatura)modelo.get(pos)).getEnergia(), 
                    ((Criatura)modelo.get(pos)).getMax_edad(), 
                    ((Criatura)modelo.get(pos)).getRegion(), 
                    ((Criatura)modelo.get(pos)).getVidas());
        ac.getListacriaturas().add(c);
        ac.escArchCriaturas();
        JOptionPane.showMessageDialog(this, "Guardado");
        jmi_entrar.setEnabled(true);
        txt_key.setText("");
        txt_nuevacontrasena.setText("");
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btn_agregarmundo3ActionPerformed

    private void btn_mostrarmundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarmundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mostrarmundoActionPerformed

    private void btn_agregarcri1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcri1ActionPerformed
        // TODO add your handling code here:
        String nombre=txt_nombrecriatura1.getText(),region=txt_region1.getText(),objeto=txt_objetos1.getText();
        int energia=Integer.parseInt(txt_cantidadenergia1.getText()),anios=Integer.parseInt(txt_maxanios1.getText()),vidas=Integer.parseInt(txt_vivas1.getText());
        
        try {
            Criatura c = new Criatura(nombre, energia, vidas, region, vidas);
            c.addObjeto(txt_objetos1.getText());
            DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
        modelo.addElement(c);
        jl_criaturas.setModel(modelo);
        DefaultComboBoxModel modelocmb =(DefaultComboBoxModel) cmb_criaturas.getModel();
            modelocmb.addElement(c);
        cmb_criaturas.setModel(modelocmb);
        txt_nombrecriatura1.setText("");
        txt_region1.setText("");
        txt_objetos1.setText("");
        txt_cantidadenergia1.setText("");
        txt_maxanios1.setText("");
        txt_vivas1.setText("");
        
            
            JOptionPane.showMessageDialog(this, "Criatura modificada");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btn_agregarcri1ActionPerformed

    private void cmb_criaturasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_criaturasItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange()==2) {
            Criatura c = (Criatura) cmb_criaturas.getSelectedItem();
            txt_nombrecriatura1.setText(c.getNombre().toString());
            txt_cantidadenergia1.setText(Integer.toString(c.getEnergia()));
            txt_maxanios1.setText(Integer.toString(c.getMax_edad()));
            txt_region1.setText(c.getRegion());
            txt_vivas1.setText(Integer.toString(c.getVidas()));
            txt_objetos1.setText(c.getObjetos().toString());
        }
    }//GEN-LAST:event_cmb_criaturasItemStateChanged

    private void cmb_mundosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_mundosItemStateChanged
        // TODO add your handling code here:
        int pos = cmb_mundos.getSelectedIndex();
        if (evt.getStateChange()==2) {
            
        }
    }//GEN-LAST:event_cmb_mundosItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int pos = jl_criaturas.getSelectedIndex();
        DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
        File fichero = new File("./Criaturas/"+((Criatura)modelo.get(pos)).getNombre()+".txt");
        try{
               if (fichero.delete()) {
                JOptionPane.showMessageDialog(this, "Archivo Eliminado");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Archivo no fue Eliminado");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Criatura c = (Criatura) cmb_criaturasmundo.getSelectedItem();
        int pos = cmb_criaturasmundo.getSelectedIndex();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmb_criaturasmundo.getModel();
        Mundo_disco md = new Mundo_disco();
        DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
        md.addCriatura(c);
        JOptionPane.showMessageDialog(this, "Criatura agregada");
        cmb_criaturasmundo.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public String cifrado(String clave){
        String contra="";
        return contra;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra;
    private javax.swing.JButton agregarmundo;
    private javax.swing.JButton btn_agregarcontra;
    private javax.swing.JButton btn_agregarcri;
    private javax.swing.JButton btn_agregarcri1;
    private javax.swing.JButton btn_agregarcriatura;
    private javax.swing.JButton btn_agregarmundo;
    private javax.swing.JButton btn_agregarmundo3;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_modificarcriatura;
    private javax.swing.JButton btn_modificarmundo;
    private javax.swing.JButton btn_mostrarmundo;
    private javax.swing.JComboBox<String> cmb_criaturas;
    private javax.swing.JComboBox<String> cmb_criaturasmundo;
    private javax.swing.JComboBox<String> cmb_elegircri;
    private javax.swing.JComboBox<String> cmb_mundos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_contra;
    private javax.swing.JDialog jd_crearcriatura;
    private javax.swing.JDialog jd_crearmundo;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_modificarcriatura;
    private javax.swing.JDialog jd_modificarmundo;
    private javax.swing.JDialog jd_mostrar;
    private javax.swing.JDialog jd_vermundos;
    private javax.swing.JList<String> jl_criaturas;
    private javax.swing.JList<String> jl_mundos;
    private javax.swing.JMenu jm_login;
    private javax.swing.JMenu jm_muestra;
    private javax.swing.JMenuItem jmi_contra;
    private javax.swing.JMenuItem jmi_entrar;
    private javax.swing.JMenuItem jmi_mostrar;
    private javax.swing.JTextField txt_cantidadenergia;
    private javax.swing.JTextField txt_cantidadenergia1;
    private javax.swing.JTextField txt_contra;
    private javax.swing.JTextField txt_key;
    private javax.swing.JTextField txt_maxanios;
    private javax.swing.JTextField txt_maxanios1;
    private javax.swing.JTextField txt_nombrecriatura;
    private javax.swing.JTextField txt_nombrecriatura1;
    private javax.swing.JTextField txt_nombremundo;
    private javax.swing.JTextField txt_nombremundo1;
    private javax.swing.JTextField txt_nuevacontrasena;
    private javax.swing.JTextField txt_objetos;
    private javax.swing.JTextField txt_objetos1;
    private javax.swing.JTextField txt_region;
    private javax.swing.JTextField txt_region1;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JTextField txt_vivas;
    private javax.swing.JTextField txt_vivas1;
    // End of variables declaration//GEN-END:variables

    String user = "xXxGranATuinxXx";
    
}
